from prometheus_client import Counter, Histogram


EVENTS_RECEIVED = Counter(
    "security_events_received_total",
    "Total number of security events received",
)

ALERTS_GENERATED = Counter(
    "security_alerts_generated_total",
    "Total number of security alerts generated",
)

ALERTS_BY_SEVERITY = Counter(
    "security_alerts_by_severity_total",
    "Total number of security alerts generated by severity",
    ["severity"],
)

EVENTS_BY_TYPE = Counter(
    "security_events_by_type_total",
    "Total number of security events received by event type",
    ["event_type"],
)

HTTP_REQUESTS = Counter(
    "http_requests_total",
    "Total number of HTTP requests",
    ["method", "path", "status"],
)

HTTP_REQUEST_DURATION = Histogram(
    "http_request_duration_seconds",
    "HTTP request duration in seconds",
    ["method", "path"],
)

DETECTION_RULE_TRIGGERS = Counter(
    "detection_rule_triggers_total",
    "Total number of detection rule triggers",
    ["rule", "severity"],
)
